/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectiveSsrSpaRouteImport } from './routes/selective-ssr/spa'
import { Route as SelectiveSsrFullRouteImport } from './routes/selective-ssr/full'
import { Route as SelectiveSsrDataOnlyRouteImport } from './routes/selective-ssr/data-only'
import { Route as LoaderVsClientToBeRouteImport } from './routes/loader-vs-client/to-be'
import { Route as LoaderVsClientAsIsRouteImport } from './routes/loader-vs-client/as-is'
import { Route as BlockingVsDeferredToBeRouteImport } from './routes/blocking-vs-deferred/to-be'
import { Route as BlockingVsDeferredAsIsRouteImport } from './routes/blocking-vs-deferred/as-is'
import { Route as CachePreloadToBeIndexRouteImport } from './routes/cache-preload/to-be/index'
import { Route as CachePreloadAsIsIndexRouteImport } from './routes/cache-preload/as-is/index'
import { Route as CachePreloadToBeIdRouteImport } from './routes/cache-preload/to-be/$id'
import { Route as CachePreloadAsIsIdRouteImport } from './routes/cache-preload/as-is/$id'
import { ServerRoute as ApiSpacesServerRouteImport } from './routes/api/spaces'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectiveSsrSpaRoute = SelectiveSsrSpaRouteImport.update({
  id: '/selective-ssr/spa',
  path: '/selective-ssr/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectiveSsrFullRoute = SelectiveSsrFullRouteImport.update({
  id: '/selective-ssr/full',
  path: '/selective-ssr/full',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectiveSsrDataOnlyRoute = SelectiveSsrDataOnlyRouteImport.update({
  id: '/selective-ssr/data-only',
  path: '/selective-ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const LoaderVsClientToBeRoute = LoaderVsClientToBeRouteImport.update({
  id: '/loader-vs-client/to-be',
  path: '/loader-vs-client/to-be',
  getParentRoute: () => rootRouteImport,
} as any)
const LoaderVsClientAsIsRoute = LoaderVsClientAsIsRouteImport.update({
  id: '/loader-vs-client/as-is',
  path: '/loader-vs-client/as-is',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockingVsDeferredToBeRoute = BlockingVsDeferredToBeRouteImport.update({
  id: '/blocking-vs-deferred/to-be',
  path: '/blocking-vs-deferred/to-be',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockingVsDeferredAsIsRoute = BlockingVsDeferredAsIsRouteImport.update({
  id: '/blocking-vs-deferred/as-is',
  path: '/blocking-vs-deferred/as-is',
  getParentRoute: () => rootRouteImport,
} as any)
const CachePreloadToBeIndexRoute = CachePreloadToBeIndexRouteImport.update({
  id: '/cache-preload/to-be/',
  path: '/cache-preload/to-be/',
  getParentRoute: () => rootRouteImport,
} as any)
const CachePreloadAsIsIndexRoute = CachePreloadAsIsIndexRouteImport.update({
  id: '/cache-preload/as-is/',
  path: '/cache-preload/as-is/',
  getParentRoute: () => rootRouteImport,
} as any)
const CachePreloadToBeIdRoute = CachePreloadToBeIdRouteImport.update({
  id: '/cache-preload/to-be/$id',
  path: '/cache-preload/to-be/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CachePreloadAsIsIdRoute = CachePreloadAsIsIdRouteImport.update({
  id: '/cache-preload/as-is/$id',
  path: '/cache-preload/as-is/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpacesServerRoute = ApiSpacesServerRouteImport.update({
  id: '/api/spaces',
  path: '/api/spaces',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocking-vs-deferred/as-is': typeof BlockingVsDeferredAsIsRoute
  '/blocking-vs-deferred/to-be': typeof BlockingVsDeferredToBeRoute
  '/loader-vs-client/as-is': typeof LoaderVsClientAsIsRoute
  '/loader-vs-client/to-be': typeof LoaderVsClientToBeRoute
  '/selective-ssr/data-only': typeof SelectiveSsrDataOnlyRoute
  '/selective-ssr/full': typeof SelectiveSsrFullRoute
  '/selective-ssr/spa': typeof SelectiveSsrSpaRoute
  '/cache-preload/as-is/$id': typeof CachePreloadAsIsIdRoute
  '/cache-preload/to-be/$id': typeof CachePreloadToBeIdRoute
  '/cache-preload/as-is': typeof CachePreloadAsIsIndexRoute
  '/cache-preload/to-be': typeof CachePreloadToBeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocking-vs-deferred/as-is': typeof BlockingVsDeferredAsIsRoute
  '/blocking-vs-deferred/to-be': typeof BlockingVsDeferredToBeRoute
  '/loader-vs-client/as-is': typeof LoaderVsClientAsIsRoute
  '/loader-vs-client/to-be': typeof LoaderVsClientToBeRoute
  '/selective-ssr/data-only': typeof SelectiveSsrDataOnlyRoute
  '/selective-ssr/full': typeof SelectiveSsrFullRoute
  '/selective-ssr/spa': typeof SelectiveSsrSpaRoute
  '/cache-preload/as-is/$id': typeof CachePreloadAsIsIdRoute
  '/cache-preload/to-be/$id': typeof CachePreloadToBeIdRoute
  '/cache-preload/as-is': typeof CachePreloadAsIsIndexRoute
  '/cache-preload/to-be': typeof CachePreloadToBeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocking-vs-deferred/as-is': typeof BlockingVsDeferredAsIsRoute
  '/blocking-vs-deferred/to-be': typeof BlockingVsDeferredToBeRoute
  '/loader-vs-client/as-is': typeof LoaderVsClientAsIsRoute
  '/loader-vs-client/to-be': typeof LoaderVsClientToBeRoute
  '/selective-ssr/data-only': typeof SelectiveSsrDataOnlyRoute
  '/selective-ssr/full': typeof SelectiveSsrFullRoute
  '/selective-ssr/spa': typeof SelectiveSsrSpaRoute
  '/cache-preload/as-is/$id': typeof CachePreloadAsIsIdRoute
  '/cache-preload/to-be/$id': typeof CachePreloadToBeIdRoute
  '/cache-preload/as-is/': typeof CachePreloadAsIsIndexRoute
  '/cache-preload/to-be/': typeof CachePreloadToBeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocking-vs-deferred/as-is'
    | '/blocking-vs-deferred/to-be'
    | '/loader-vs-client/as-is'
    | '/loader-vs-client/to-be'
    | '/selective-ssr/data-only'
    | '/selective-ssr/full'
    | '/selective-ssr/spa'
    | '/cache-preload/as-is/$id'
    | '/cache-preload/to-be/$id'
    | '/cache-preload/as-is'
    | '/cache-preload/to-be'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocking-vs-deferred/as-is'
    | '/blocking-vs-deferred/to-be'
    | '/loader-vs-client/as-is'
    | '/loader-vs-client/to-be'
    | '/selective-ssr/data-only'
    | '/selective-ssr/full'
    | '/selective-ssr/spa'
    | '/cache-preload/as-is/$id'
    | '/cache-preload/to-be/$id'
    | '/cache-preload/as-is'
    | '/cache-preload/to-be'
  id:
    | '__root__'
    | '/'
    | '/blocking-vs-deferred/as-is'
    | '/blocking-vs-deferred/to-be'
    | '/loader-vs-client/as-is'
    | '/loader-vs-client/to-be'
    | '/selective-ssr/data-only'
    | '/selective-ssr/full'
    | '/selective-ssr/spa'
    | '/cache-preload/as-is/$id'
    | '/cache-preload/to-be/$id'
    | '/cache-preload/as-is/'
    | '/cache-preload/to-be/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockingVsDeferredAsIsRoute: typeof BlockingVsDeferredAsIsRoute
  BlockingVsDeferredToBeRoute: typeof BlockingVsDeferredToBeRoute
  LoaderVsClientAsIsRoute: typeof LoaderVsClientAsIsRoute
  LoaderVsClientToBeRoute: typeof LoaderVsClientToBeRoute
  SelectiveSsrDataOnlyRoute: typeof SelectiveSsrDataOnlyRoute
  SelectiveSsrFullRoute: typeof SelectiveSsrFullRoute
  SelectiveSsrSpaRoute: typeof SelectiveSsrSpaRoute
  CachePreloadAsIsIdRoute: typeof CachePreloadAsIsIdRoute
  CachePreloadToBeIdRoute: typeof CachePreloadToBeIdRoute
  CachePreloadAsIsIndexRoute: typeof CachePreloadAsIsIndexRoute
  CachePreloadToBeIndexRoute: typeof CachePreloadToBeIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/spaces': typeof ApiSpacesServerRoute
}
export interface FileServerRoutesByTo {
  '/api/spaces': typeof ApiSpacesServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/spaces': typeof ApiSpacesServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/spaces'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/spaces'
  id: '__root__' | '/api/spaces'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSpacesServerRoute: typeof ApiSpacesServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/spa': {
      id: '/selective-ssr/spa'
      path: '/selective-ssr/spa'
      fullPath: '/selective-ssr/spa'
      preLoaderRoute: typeof SelectiveSsrSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/full': {
      id: '/selective-ssr/full'
      path: '/selective-ssr/full'
      fullPath: '/selective-ssr/full'
      preLoaderRoute: typeof SelectiveSsrFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/data-only': {
      id: '/selective-ssr/data-only'
      path: '/selective-ssr/data-only'
      fullPath: '/selective-ssr/data-only'
      preLoaderRoute: typeof SelectiveSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loader-vs-client/to-be': {
      id: '/loader-vs-client/to-be'
      path: '/loader-vs-client/to-be'
      fullPath: '/loader-vs-client/to-be'
      preLoaderRoute: typeof LoaderVsClientToBeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loader-vs-client/as-is': {
      id: '/loader-vs-client/as-is'
      path: '/loader-vs-client/as-is'
      fullPath: '/loader-vs-client/as-is'
      preLoaderRoute: typeof LoaderVsClientAsIsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocking-vs-deferred/to-be': {
      id: '/blocking-vs-deferred/to-be'
      path: '/blocking-vs-deferred/to-be'
      fullPath: '/blocking-vs-deferred/to-be'
      preLoaderRoute: typeof BlockingVsDeferredToBeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocking-vs-deferred/as-is': {
      id: '/blocking-vs-deferred/as-is'
      path: '/blocking-vs-deferred/as-is'
      fullPath: '/blocking-vs-deferred/as-is'
      preLoaderRoute: typeof BlockingVsDeferredAsIsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache-preload/to-be/': {
      id: '/cache-preload/to-be/'
      path: '/cache-preload/to-be'
      fullPath: '/cache-preload/to-be'
      preLoaderRoute: typeof CachePreloadToBeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache-preload/as-is/': {
      id: '/cache-preload/as-is/'
      path: '/cache-preload/as-is'
      fullPath: '/cache-preload/as-is'
      preLoaderRoute: typeof CachePreloadAsIsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache-preload/to-be/$id': {
      id: '/cache-preload/to-be/$id'
      path: '/cache-preload/to-be/$id'
      fullPath: '/cache-preload/to-be/$id'
      preLoaderRoute: typeof CachePreloadToBeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache-preload/as-is/$id': {
      id: '/cache-preload/as-is/$id'
      path: '/cache-preload/as-is/$id'
      fullPath: '/cache-preload/as-is/$id'
      preLoaderRoute: typeof CachePreloadAsIsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/spaces': {
      id: '/api/spaces'
      path: '/api/spaces'
      fullPath: '/api/spaces'
      preLoaderRoute: typeof ApiSpacesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockingVsDeferredAsIsRoute: BlockingVsDeferredAsIsRoute,
  BlockingVsDeferredToBeRoute: BlockingVsDeferredToBeRoute,
  LoaderVsClientAsIsRoute: LoaderVsClientAsIsRoute,
  LoaderVsClientToBeRoute: LoaderVsClientToBeRoute,
  SelectiveSsrDataOnlyRoute: SelectiveSsrDataOnlyRoute,
  SelectiveSsrFullRoute: SelectiveSsrFullRoute,
  SelectiveSsrSpaRoute: SelectiveSsrSpaRoute,
  CachePreloadAsIsIdRoute: CachePreloadAsIsIdRoute,
  CachePreloadToBeIdRoute: CachePreloadToBeIdRoute,
  CachePreloadAsIsIndexRoute: CachePreloadAsIsIndexRoute,
  CachePreloadToBeIndexRoute: CachePreloadToBeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSpacesServerRoute: ApiSpacesServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
